### PR TITLE
First ODP white label microsite and wiki commit

### PR DESCRIPTION
**Pull request by mcleo-d**
### Description
This is the first push of a white label ODP microsite as part of epic #37 into the development feature branch **odp-issues-37-docusaurus-white-label-wiki**.

- https://github.com/finos/open-developer-platform/tree/odp-issues-37-docusaurus-white-label-wiki

### Ongoing Development
The ongoing development of the ODP Docusaurus microsite and wiki should happen in **odp-issues-37-docusaurus-white-label-wiki** until the first microsite can be published from master.

### Delivered Story
This PR delivers **Build a white label microsite with Docusaurus (for FINOS ODP)** as part of epic #37.

### CODE REVIEW

**Comment by maoo** [comment]
Great work here @mcleo-d , thank you!

I've reviewed this PR, and everything seems ready to merge; just few questions:
- Not sure if/how the Dockerfile and docker-compose files are used, we normally don't include it as we dont use it, nor we instruct our community to do so
- We have never used the Docusaurus blog feature, as we prefer to consolidate all blog material into www.finos.org

Please let me know if these items were intentional; if not, feel free to make updates on your branch and I'll proceed to the merging afterwards. TY!

**Comment by mcleo-d** [comment]
Thanks @maoo - Let me amend and update before merging 👍

**Comment by mcleo-d** [comment]
Hi @maoo - I've committed to the following branch **odp-issues-37-docusaurus-white-label-wiki**

- Removed Docker related files from project root
- Disabled blog feature in siteConfig.js

Please note, the blog docs structure is still part of the project, as demonstrated by the FDC3 microsite.

Let me know if anything else should be done.

James.

**Comment by maoo** [comment]
LGTM! Merging into `finos:odp-issues-37-docusaurus-white-label-wiki` branch, so we can refine and test the build part, before merging into `master`. TY!

**Pull request merged**
